from .import patient
from .import doctor
from .import tag
from .import appointment
from .import config_settings
from .import operation
from .import sale_order
from .import sale_report
from .import group
from .import account_move